name: Send Weekly Telegram Poll

on:
  schedule:
    - cron: '45 21 * * 0' # Щонеділі о 23:45 за Києвом (UTC 21:45)
  workflow_dispatch:      # Кнопка для ручного запуску

jobs:
  send_poll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install library
        run: pip install python-telegram-bot

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python create_poll.py