name: Update Google Sheet Schedule

on:
  schedule:
    # Формат POSIX cron (хвилини години день місяць день_тижня)
    # Наприклад, кожні 6 годин:
    - cron: '0 */6 * * *'
  workflow_dispatch: # Дозволяє запускати скрипт вручну кнопкою

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        # env:
        #   GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
<<<<<<< HEAD
        run: python main.py
=======
        run: python main.py
>>>>>>> 499c4f385ea39884d1be1ca6a0b042dfc26f5d5c
