name: Send Weekly Telegram Poll

on:
  schedule:
    # 00 хвилин, 09 годин, будь-який день, будь-який місяць, 1 — це Понеділок
    - cron: '0 9 * * 1'
  workflow_dispatch:      # Кнопка для ручного запуску

jobs:
  send_poll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install library
        run: pip install python-telegram-bot

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python main.py